### ISSUE TITLE
【iOS】实现requiresMainQueueSetup消除警告

### ISSUE THREAD

**Issue by voids** [LiteAVSDK/TRTC_ReactNative#1]
iOS版本：14.8.1
ReactNative版本：0.66.3

模拟器与真机均报如下Warning：
Module TrtcReactNativeSdk requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

看起来是重写了init，建议需要实现requiresMainQueueSetup

```Objective-C
+ (BOOL)requiresMainQueueSetup{
  return YES;
}
```

**Comment by c1avie** [comment]
收到，我们看一下
