### ISSUE TITLE
打包报错误

### ISSUE THREAD

**Issue by dagouzhi** [LiteAVSDK/TRTC_ReactNative#3]
![image](https://user-images.githubusercontent.com/9784729/161186261-ff8ef6b1-4a31-476f-a0d1-7b5a360cf5b0.png)
![image](https://user-images.githubusercontent.com/9784729/161186294-cf343df3-79a0-4805-9eed-7142de423ece.png)

**Comment by c1avie** [comment]
旧项目已经废弃，请使用TRTC-SIMPLE-DEMO重新编译调试
